apiVersion: v1
kind: Service
metadata:
  name: cache
  namespace: velox
  labels:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: velox
spec:
  ports:
    - name: cache
      port: 6379
      targetPort: cache
  selector:
    app.kubernetes.io/name: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: velox
  labels:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: velox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cache
        app.kubernetes.io/part-of: velox
    spec:
      containers:
        - name: cache
          image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.23.1
          imagePullPolicy: IfNotPresent
          args: ["--bind", "0.0.0.0", "--port", "6379"]
          ports:
            - name: cache
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: cache
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: cache
            initialDelaySeconds: 20
            periodSeconds: 20
