apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orderservice
  labels:
    app.kubernetes.io/name: orderservice
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seatservice
  labels:
    app.kubernetes.io/name: seatservice
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewservice
  labels:
    app.kubernetes.io/name: viewservice
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache
  labels:
    app.kubernetes.io/name: cache
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker
  labels:
    app.kubernetes.io/name: broker
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker-topics-init
  labels:
    app.kubernetes.io/name: broker-topics-init
    app.kubernetes.io/part-of: velox
automountServiceAccountToken: false
